UPLOADING LIBRARIES

In [340]:
# Importing libraries
# we shall import pandas libraries
import pandas as pd

# we shall also import the numpy libraries
import numpy as np

Importing Files to read CSV file, 

The first dataset contains Distribution Of Assistive Devices And Services By National Council For Persons With Disabilities (NCPWD)
The dataset is as by 06/30/2016

The second dataset contains Percentage_Distribution_of_Population_by_type_of_Disability_County_Estimates%2C2005_6

In [341]:
# we shall import the dataset into python workspace
# and create a dataframe from the csv file

url = "Distribution_Of_Assistive_Devices_And_Services_By_National_Council_For_Persons_With_Disabilities_(NCPWD).csv"
Assistive_Devices = pd.read_csv(url)
Assistive_Devices.head(10)

,SUB_COUNTY,COUNTY,DISABILITY,SERVICE_PROVIDER,COST_OF_THE_DEVICE/SERVICE_KSHs,DISTRIBUTED_DEVICE/SERVICE,FINANCIAL_YEAR_ENDING,CENTROID_X,CENTROID_Y,OBJECTID
0,Bungoma,Bungoma,Physical,Association for the Physically Disabled of Ken...,500,Adjustable Walking Stick,6/30/2016,34.640064,0.751267,0
1,Bungoma East,Bungoma,Physical,Association for the Physically Disabled of Ken...,2900,Knee Cap/Elbow Crutches,6/30/2016,34.640064,0.751267,1
2,Bungoma East,Bungoma,Physical,Association for the Physically Disabled of Ken...,19000,Tricycle/Walkind Stick,6/30/2016,34.640064,0.751267,2
3,Bungoma,Bungoma,Cerebral Palsy,Association for the Physically Disabled of Ken...,21000,Special Seat,6/30/2016,34.640064,0.751267,3
4,Embu East,Embu,Physical,no professional report,-,Surgical Boot And Crutches,6/30/2016,37.623862,-0.599584,4
5,Embu Eest,Embu,Physical/Visual/Mental,Association for the Physically Disabled of Ken...,21000,Wheelchair,6/30/2016,37.623862,-0.599584,5
6,Garissa,Garissa,Physical,Garissa Orthopaedic services,31320,C.P Wheelchair,6/30/2016,40.165977,-0.481350,6
7,Garissa Central,Garissa,Physical/Speech,Garissa Orthopaedic services,31320,C.P Wheelchair,6/30/2016,40.165977,-0.481350,7
8,Garissa,Garissa,Physical,Garissa Orthopaedic services,31320,C.P Wheelchair,6/30/2016,40.165977,-0.481350,8
9,Homa Bay,Homa Bay,Physical,Association for the Physically Disabled of Ken...,1940,Elbow Crutches,6/30/2016,34.442563,-0.569462,9

In [342]:
# we shall import the dataset into python workspace
# and create a dataframe from the csv file

url = "Percentage_Distribution_of_Population_by_type_of_Disability_County_Estimates%2C2005_6.csv"
Percentage_Disability_per_County = pd.read_csv(url)
Percentage_Disability_per_County.head()

,County,Missing_Hand,Missing_Foot,Lame,Blind,Deaf,Dumb,Mental,Paralyzed,Other,Total_Count,Location_1,OBJECTID
0,Baringo,10.9%,2.8%,30.9%,2.6%,1%,3.8%,12.4%,54.2%,10.9%,6512.1,"(0.512912, 35.952537)",0
1,Bomet,0%,0%,29.2%,10%,8.1%,8.1%,14.2%,0.3%,38.7%,6538.0,"(-0.690131, 35.278005)",1
2,Bungoma,12.3%,0%,49.2%,0%,2.3%,20.8%,12.7%,0%,21.9%,13170.6,"(0.737046, 34.672536)",2
3,Busia,0%,0%,14.3%,12.3%,4.6%,35.5%,4.8%,14.8%,31.4%,6655.5,"(0.428414, 34.210571)",3
4,Elgeyo Marakwet,0%,0%,31.7%,0%,35.7%,0%,20%,12.6%,7.4%,3599.9,"(0.806011, 35.564093)",4

**DATA** **CLEANING**

In [343]:
# Checking information of the dataset first dataset
Assistive_Devices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 10 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   SUB_COUNTY                       236 non-null    object
 1   COUNTY                           236 non-null    object
 2   DISABILITY                       236 non-null    object
 3   SERVICE_PROVIDER                 236 non-null    object
 4   COST_OF_THE_DEVICE/SERVICE_KSHs  236 non-null    object
 5   DISTRIBUTED_DEVICE/SERVICE       236 non-null    object
 6   FINANCIAL_YEAR_ENDING            236 non-null    object
 7   CENTROID_X                       236 non-null    float64
 8   CENTROID_Y                       236 non-null    float64
 9   OBJECTID                         236 non-null    int64
dtypes: float64(2), int64(1), object(7)
memory usage: 18.6+ KB

In [344]:
# Changing the cases of the columns to lower case 

Assistive_Devices.columns = Assistive_Devices.columns.str.strip().str.lower()
Assistive_Devices.head(2)

,sub_county,county,disability,service_provider,cost_of_the_device/service_kshs,distributed_device/service,financial_year_ending,centroid_x,centroid_y,objectid
0,Bungoma,Bungoma,Physical,Association for the Physically Disabled of Ken...,500,Adjustable Walking Stick,6/30/2016,34.640064,0.751267,0
1,Bungoma East,Bungoma,Physical,Association for the Physically Disabled of Ken...,2900,Knee Cap/Elbow Crutches,6/30/2016,34.640064,0.751267,1

In [345]:
# Finding if there are any missing data in the dataset

Assistive_Devices.isnull().any().sum()

0

In [346]:
# we remove any duplicates in the dataframe

Assistive_Divices_non_duplicates = Assistive_Devices.drop_duplicates

In [347]:
# Removing any irrelevant columns
# Data columns that we will not need in our analysis
Assistive_Devices.drop(['financial_year_ending',	'centroid_x',	'centroid_y',	'objectid'], axis=1, inplace=True)
Assistive_Devices

,sub_county,county,disability,service_provider,cost_of_the_device/service_kshs,distributed_device/service
0,Bungoma,Bungoma,Physical,Association for the Physically Disabled of Ken...,500,Adjustable Walking Stick
1,Bungoma East,Bungoma,Physical,Association for the Physically Disabled of Ken...,2900,Knee Cap/Elbow Crutches
2,Bungoma East,Bungoma,Physical,Association for the Physically Disabled of Ken...,19000,Tricycle/Walkind Stick
3,Bungoma,Bungoma,Cerebral Palsy,Association for the Physically Disabled of Ken...,21000,Special Seat
4,Embu East,Embu,Physical,no professional report,-,Surgical Boot And Crutches
...,...,...,...,...,...,...
231,Eldoret,Uasin Gishu,Physical,Uasin Gishu District Hospital,4600,Callipers/Walking Stick
232,Eldoret,Uasin Gishu,Physical,Uasin Gishu District Hospital,4600,Callipers/Walking Stick
233,Eldoret East,Uasin Gishu,Physical,no professional report,1500,Walking Cane
234,Habaswei,Wajir,Physical,Bio-Orthotic & Prosthetics services,91000,Callipers/Polio Boots
235,Habaswei,Wajir,Physical,Bio-Orthotic & Prosthetics services,91000,Callipers/Polio Boots

In [348]:
# Removing any irrelevant rows
# Data rows that we will not need in our analysis
Percentage_Disability_per_County = Percentage_Disability_per_County[Percentage_Disability_per_County['County'] != "Kenya average"]

In [349]:
# Finding the number of objects in the dataset.
Assistive_Devices.count()

sub_county                         236
county                             236
disability                         236
service_provider                   236
cost_of_the_device/service_kshs    236
distributed_device/service         236
dtype: int64

In [350]:
# Checking for the information on the dataset second dataset

Percentage_Disability_per_County.head()

,County,Missing_Hand,Missing_Foot,Lame,Blind,Deaf,Dumb,Mental,Paralyzed,Other,Total_Count,Location_1,OBJECTID
0,Baringo,10.9%,2.8%,30.9%,2.6%,1%,3.8%,12.4%,54.2%,10.9%,6512.1,"(0.512912, 35.952537)",0
1,Bomet,0%,0%,29.2%,10%,8.1%,8.1%,14.2%,0.3%,38.7%,6538.0,"(-0.690131, 35.278005)",1
2,Bungoma,12.3%,0%,49.2%,0%,2.3%,20.8%,12.7%,0%,21.9%,13170.6,"(0.737046, 34.672536)",2
3,Busia,0%,0%,14.3%,12.3%,4.6%,35.5%,4.8%,14.8%,31.4%,6655.5,"(0.428414, 34.210571)",3
4,Elgeyo Marakwet,0%,0%,31.7%,0%,35.7%,0%,20%,12.6%,7.4%,3599.9,"(0.806011, 35.564093)",4

In [351]:
# Checking for any missing data in the dataset

Percentage_Disability_per_County.isnull().any().sum()

0

In [352]:
# Dropping any columns that are not relevant for our analysis
Percentage_Disability_per_County.drop(['Location_1', 'OBJECTID'], axis=1, inplace=True)
Percentage_Disability_per_County

,County,Missing_Hand,Missing_Foot,Lame,Blind,Deaf,Dumb,Mental,Paralyzed,Other,Total_Count
0,Baringo,10.9%,2.8%,30.9%,2.6%,1%,3.8%,12.4%,54.2%,10.9%,6512.1
1,Bomet,0%,0%,29.2%,10%,8.1%,8.1%,14.2%,0.3%,38.7%,6538.0
2,Bungoma,12.3%,0%,49.2%,0%,2.3%,20.8%,12.7%,0%,21.9%,13170.6
3,Busia,0%,0%,14.3%,12.3%,4.6%,35.5%,4.8%,14.8%,31.4%,6655.5
4,Elgeyo Marakwet,0%,0%,31.7%,0%,35.7%,0%,20%,12.6%,7.4%,3599.9
5,Embu,0%,0%,55.1%,0%,0%,3%,3%,2.5%,41.8%,6287.4
6,Garissa,0%,37.1%,0%,0%,0%,0%,11.3%,11.3%,51.6%,1864.1
7,Homa Bay,2.1%,0%,20.9%,6.7%,6.3%,5.2%,11.3%,9%,48.3%,23696.8
8,Isiolo,13.9%,3.3%,32.6%,38.6%,12.9%,0%,0%,2%,19.8%,2154.4
9,Kajiado,0%,0%,26.9%,19%,0%,0%,27.6%,0%,45.5%,3250.3
10,Kakamega,1%,0%,30.1%,6.8%,0.5%,4.8%,3.6%,6.3%,51.7%,27468.9
11,Kericho,0%,0%,0%,4.8%,0%,0%,0%,21.7%,73.6%,3055.8
12,Kiambu,0%,0%,0%,10.1%,0%,0%,70.7%,7.6%,11.6%,10099.9
13,Kilifi,2.5%,0%,35.5%,18.2%,13.8%,7.1%,29.3%,9.9%,2.5%,6996.6
14,Kirinyaga,0%,0%,4.2%,0%,0%,0%,66.4%,33.6%,0%,2522.8
15,Kisii,0%,6.6%,7%,12.7%,10.2%,6.6%,22.1%,11%,23.8%,9627.8
16,Kisumu,7.6%,0%,32.7%,0%,0%,4.5%,17.7%,3%,41.4%,20026.3
17,Kitui,0%,9.3%,11%,17.2%,0%,36.4%,17.7%,19.4%,7.6%,4403.0
18,Kwale,0%,9.1%,14.6%,7.4%,0%,19.9%,50.5%,6.4%,19.5%,8503.0
19,Laikipia,0%,0%,45.2%,0%,0%,54.8%,0%,0%,0%,1825.7
20,Lamu,0%,0%,0%,0%,0%,26.1%,8.6%,2.9%,65.3%,524.9
21,Machakos,0%,0%,12.6%,0%,0%,10.3%,18.8%,18%,58.9%,23460.4
22,Makueni,0%,0%,16.7%,31.5%,4.7%,9.2%,19.7%,10.9%,30.5%,15475.4
23,Mandera,0%,1.4%,8.9%,14%,25.9%,11.8%,29.6%,9.2%,10.9%,3343.5
24,Marsabit,1.5%,9.7%,16.2%,8.6%,18.8%,9.6%,11.6%,23.9%,18.3%,3931.5
25,Meru,0%,0%,34.7%,0%,0%,11.6%,12.3%,4%,57.2%,19166.3
26,Migori,6%,6.9%,29.4%,1.4%,4%,0%,8.6%,15.4%,30.1%,15359.3
27,Mombasa,0%,0%,9.3%,24.5%,0%,1%,16.8%,25.8%,22.6%,5413.4
28,Murang'a,0%,0%,16.5%,0%,17.2%,41.4%,20.3%,10.1%,15.5%,8512.1
29,Nairobi,0%,12.6%,20.4%,0%,17.5%,7.6%,29.6%,1.1%,18.9%,14936.2
30,Nakuru,0.4%,0%,55%,0%,0%,8.4%,33.6%,12.7%,15.7%,21598.0
31,Nandi,0%,9.1%,25.7%,7%,9.1%,0%,0%,0%,49.1%,11530.7
32,Narok,5.4%,0.6%,11.3%,2.5%,12.2%,22.3%,23.7%,32.5%,14.4%,7986.1
33,Nyamira,0%,0%,21.1%,0%,50.2%,54.5%,0%,0%,0%,4727.3
34,Nyandarua,21.2%,0%,28.7%,0%,27.9%,0%,22.2%,0%,0%,2369.6
35,Nyeri,0%,16.1%,41.2%,16.1%,25.1%,9.8%,32.9%,0%,0%,2392.6
36,Samburu,11.6%,10%,31.6%,22%,10.3%,7.3%,7.1%,0%,0%,2574.9
37,Siaya,0%,0%,22.4%,29.4%,0%,5.7%,14.5%,10%,23.6%,6279.4
38,Taita Taveta,0%,3.7%,15.4%,0%,0%,13.3%,83.1%,20.4%,5.9%,3709.8
39,Tana River,0%,0%,42.9%,21.2%,16.2%,7.3%,32.6%,9.2%,8.1%,3699.8
40,Tharaka Nithi,0%,0%,0%,0%,29.3%,29.3%,41.4%,0%,29.3%,420.1
41,Trans Nzoia,0%,0%,0%,11.3%,0%,0%,20.5%,0%,68.2%,8251.9
42,Turkana,0%,0%,0%,35.5%,7.8%,0%,0%,92.2%,0%,1733.1
43,Uasin Gishu,0%,0%,18.6%,0%,0%,0%,27.3%,7.2%,58.1%,9281.6
44,Vihiga,0%,0%,30.2%,19.7%,12.7%,1.1%,8%,0%,26.9%,23490.6
45,Wajir,1.3%,5.2%,50.5%,8%,8%,17.8%,12.7%,15.8%,0%,9276.5
46,West Pokot,0%,14%,29.5%,21.1%,0%,0%,0%,30.9%,12.6%,4874.2

In [353]:
# Checking the information on the dataframe

Percentage_Disability_per_County.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 47 entries, 0 to 46
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   County        47 non-null     object
 1   Missing_Hand  47 non-null     object
 2   Missing_Foot  47 non-null     object
 3   Lame          47 non-null     object
 4   Blind         47 non-null     object
 5   Deaf          47 non-null     object
 6   Dumb          47 non-null     object
 7   Mental        47 non-null     object
 8   Paralyzed     47 non-null     object
 9   Other         47 non-null     object
 10  Total_Count   47 non-null     float64
dtypes: float64(1), object(10)
memory usage: 4.4+ KB

In [354]:
# Converting the dataset columns to lower case

Percentage_Disability_per_County.columns = Percentage_Disability_per_County.columns.str.strip().str.lower()
Percentage_Disability_per_County.head(2)

,county,missing_hand,missing_foot,lame,blind,deaf,dumb,mental,paralyzed,other,total_count
0,Baringo,10.9%,2.8%,30.9%,2.6%,1%,3.8%,12.4%,54.2%,10.9%,6512.1
1,Bomet,0%,0%,29.2%,10%,8.1%,8.1%,14.2%,0.3%,38.7%,6538.0

In [355]:
# Converting the object data to integers

Percentage_Disability_per_County['missing_hand'] = Percentage_Disability_per_County['missing_hand'].str.replace("%","").apply(pd.to_numeric)
Percentage_Disability_per_County['missing_foot'] = Percentage_Disability_per_County['missing_foot'].str.replace("%","").apply(pd.to_numeric)
Percentage_Disability_per_County['lame'] = Percentage_Disability_per_County['lame'].str.replace("%","").apply(pd.to_numeric)
Percentage_Disability_per_County['blind'] = Percentage_Disability_per_County['blind'].str.replace("%","").apply(pd.to_numeric)
Percentage_Disability_per_County['deaf'] = Percentage_Disability_per_County['deaf'].str.replace("%","").apply(pd.to_numeric)
Percentage_Disability_per_County['dumb'] = Percentage_Disability_per_County['dumb'].str.replace("%","").apply(pd.to_numeric)
Percentage_Disability_per_County['mental'] = Percentage_Disability_per_County['mental'].str.replace("%","").apply(pd.to_numeric)
Percentage_Disability_per_County['paralyzed'] = Percentage_Disability_per_County['paralyzed'].str.replace("%","").apply(pd.to_numeric)
Percentage_Disability_per_County['other'] = Percentage_Disability_per_County['other'].str.replace("%","").apply(pd.to_numeric)

In [356]:
# Finding the information from the converted dataset
Percentage_Disability_per_County.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 47 entries, 0 to 46
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   county        47 non-null     object
 1   missing_hand  47 non-null     float64
 2   missing_foot  47 non-null     float64
 3   lame          47 non-null     float64
 4   blind         47 non-null     float64
 5   deaf          47 non-null     float64
 6   dumb          47 non-null     float64
 7   mental        47 non-null     float64
 8   paralyzed     47 non-null     float64
 9   other         47 non-null     float64
 10  total_count   47 non-null     float64
dtypes: float64(10), object(1)
memory usage: 4.4+ KB

In [357]:
# Creating new columns with number of persons living with disability in every county

Percentage_Disability_per_County["missing_hand"] = Percentage_Disability_per_County["missing_hand"] / 100 * Percentage_Disability_per_County['total_count']
Percentage_Disability_per_County["missing_foot"] = Percentage_Disability_per_County["missing_foot"] / 100 * Percentage_Disability_per_County['total_count']
Percentage_Disability_per_County["lame"] = Percentage_Disability_per_County["lame"] / 100 * Percentage_Disability_per_County['total_count']
Percentage_Disability_per_County["blind"] = Percentage_Disability_per_County["blind"] / 100 * Percentage_Disability_per_County['total_count']
Percentage_Disability_per_County["deaf"] = Percentage_Disability_per_County["deaf"] / 100 * Percentage_Disability_per_County['total_count']
Percentage_Disability_per_County["dumb"] = Percentage_Disability_per_County["dumb"] / 100 * Percentage_Disability_per_County['total_count']
Percentage_Disability_per_County["mental"] = Percentage_Disability_per_County["mental"] / 100 * Percentage_Disability_per_County['total_count']
Percentage_Disability_per_County["paralyzed"] = Percentage_Disability_per_County["paralyzed"] / 100 * Percentage_Disability_per_County['total_count']
Percentage_Disability_per_County["other"] = Percentage_Disability_per_County["other"] / 100 * Percentage_Disability_per_County['total_count']

types = {"missing_hand":'int', "missing_foot":'int', "lame":'int', "blind":'int', "deaf":'int', "dumb":'int', "mental":'int', "paralyzed":'int', "other":'int', "total_count":'int'}
Percentage_Disability_per_County = Percentage_Disability_per_County.astype(types)

In [358]:
# For uniformity, we replace Muranga with Murang'a 
Assistive_Devices['county'] = Assistive_Devices['county'].str.replace("Muranga","Murang'a")

**DATA** **ANALYSIS**

## 1. What is the number of persons living with the different types of disabilities in the 47 counties?

## 1.1 Identify the number of Devices per disability Category

To achieve this, we classified the devices into 6 categories as follows:
*  Lame/Missing_Hand/Missing_Foot
*  Paralysis
*  Dumb
*  Deaf
*  Mental
*  Blind

This was inspired by the classification of disabilities in the 'Percentage_Distribution_of_Population_by_type_of_Disability_County_Estimates%2C2005_6' dataset which had the same classification as above.

In [359]:
# Creating a new column that will contain the classification of the devices per disability. 
Assistive_Devices['Disability_type'] = Assistive_Devices['disability']

# Classifying the disabilities into: 'Lame/Missing_Hand/Missing_Foot', 'Paralysis', 'Dumb', 'Other', 'Deaf', 'Mental', 'Blind'

conditions = [
    (Assistive_Devices['Disability_type'] == 'Physical'),
    (Assistive_Devices['Disability_type'] == 'Cerebral Palsy'),
    (Assistive_Devices['Disability_type'] == 'Physical/Visual/Mental'),
    (Assistive_Devices['Disability_type'] == 'Physical/Speech'),
    (Assistive_Devices['Disability_type'] == 'Multiple'),
    (Assistive_Devices['Disability_type'] == 'Spinabifida'),
    (Assistive_Devices['Disability_type'] == 'Physical/Hearing'),
    (Assistive_Devices['Disability_type'] == 'Hdrocephalus'),
    (Assistive_Devices['Disability_type'] == 'Physical/Cerebral Palsy'),
    (Assistive_Devices['Disability_type'] == 'Mental'),
    (Assistive_Devices['Disability_type'] == 'Physical/Mental'),
    (Assistive_Devices['Disability_type'] == 'Physical,Speech'),
    (Assistive_Devices['Disability_type'] == 'Intellectual'),
    (Assistive_Devices['Disability_type'] == 'Physical/Visual'),
    (Assistive_Devices['Disability_type'] == 'Speech'),
    (Assistive_Devices['Disability_type'] == 'Spina Bifida & Hydrocephalus')
    ]

values = [
    'Lame/Missing_Hand/Missing_Foot',
    'Paralysis',
    'Lame/Missing_Hand/Missing_Foot',
    'Dumb',
    'Other',
    'Paralysis',
    'Deaf',
    'Paralysis',
    'Paralysis',
    'Mental',
    'Mental',
    'Dumb',
    'Mental',
    'Blind',
    'Dumb',
    'Paralysis'
]

Assistive_Devices['Disability_type'] = np.select(conditions, values)

In [360]:
# Using group by and count to identify the number of devices per disability category
no_of_devices_per_category = pd.DataFrame(Assistive_Devices['Disability_type'].groupby(Assistive_Devices['Disability_type']).agg(['count']))

# Re-indexing
no_of_devices_per_category['Type_of_disability'] = no_of_devices_per_category.index
no_of_devices_per_category.reset_index(drop=True, inplace=True)

# Renaming columns
no_of_devices_per_category.columns = ['Total_number_of_disability_devices','Type_of_disability']

# Re-arranging the columns
no_of_devices_per_category = no_of_devices_per_category[['Type_of_disability','Total_number_of_disability_devices']]

no_of_devices_per_category.sort_values(by="Total_number_of_disability_devices", ascending = 0)

               Type_of_disability  Total_number_of_disability_devices
3  Lame/Missing_Hand/Missing_Foot                                 181
6                       Paralysis                                  29
4                          Mental                                  11
5                           Other                                   8
2                            Dumb                                   4
0                           Blind                                   2
1                            Deaf                                   1

## 1.2 Identify the number of number of persons living with disabilities per disability category

In [388]:
no_of_persons_with_disabilities = pd.DataFrame(Percentage_Disability_per_County.sum())
no_of_persons_with_disabilities

                                                                                0
county                          BaringoBometBungomaBusiaElgeyo MarakwetEmbuGar...
missing_hand                                                                 7509
missing_foot                                                                 9167
lame                                                                       103425
blind                                                                       31341
deaf                                                                        23866
dumb                                                                        36366
mental                                                                      73991
paralyzed                                                                   40299
other                                                                      126968
total_count                                                                402556
Lame_Missing_Hand_Missing_Foot                                             120101

## 2. Distribution of devices per county and checking the percentage of the counties that do not have the specific devices.

**2.1 Counties that did not receive any disability devices.**

In [361]:
# Using a left join to get the counties that are only in the 'Percentage_Disability_per_County' dataset.
counties_without_devices = pd.merge(Percentage_Disability_per_County, Assistive_Devices, on='county', how='left')
counties_without_devices = counties_without_devices[counties_without_devices['disability'].isnull()]
counties_without_devices = pd.DataFrame(counties_without_devices['county'])
counties_without_devices.reset_index(drop=True, inplace=True)
counties_without_devices

             county
0           Baringo
1             Bomet
2             Busia
3   Elgeyo Marakwet
4          Kakamega
5           Kericho
6             Kisii
7              Lamu
8           Mandera
9              Meru
10            Nandi
11        Nyandarua
12          Samburu
13     Taita Taveta
14          Turkana
15           Vihiga
16       West Pokot

**2.2 Counties with disability devices.**

In [362]:
# Using an inner join to get the counties that are in both the 'Percentage_Disability_per_County' and 'Assistive_Devices' datasets.
counties_with_devices = pd.merge(Percentage_Disability_per_County, Assistive_Devices, on='county', how='inner')
counties_with_devices = pd.DataFrame(counties_with_devices['county'].unique())
counties_with_devices.columns = ['county']

counties_with_devices

           county
0         Bungoma
1            Embu
2         Garissa
3        Homa Bay
4          Isiolo
5         Kajiado
6          Kiambu
7          Kilifi
8       Kirinyaga
9          Kisumu
10          Kitui
11          Kwale
12       Laikipia
13       Machakos
14        Makueni
15       Marsabit
16         Migori
17        Mombasa
18       Murang'a
19        Nairobi
20         Nakuru
21          Narok
22        Nyamira
23          Nyeri
24          Siaya
25     Tana River
26  Tharaka Nithi
27    Trans Nzoia
28    Uasin Gishu
29          Wajir

**2.3 Obtain the percentage of the counties with Lame/Missing_Hand/Missing_Foot disabilities and without 'Lame/Missing_Hand/Missing_Foot' devices .**

In [408]:
# 1. Getting the total number of people with Lame/Missing_Hand/Missing_Foot disabilities per county from the Percentage_Disability_per_County dataset
Percentage_Disability_per_County['Lame_Missing_Hand_Missing_Foot'] = Percentage_Disability_per_County['missing_hand'] + Percentage_Disability_per_County['missing_foot'] + Percentage_Disability_per_County['lame']

# 2. Extracting the counties that have people living with Lame/Missing_Hand/Missing_Foot disabilities from the Percentage_Disability_per_County dataset
counties_with_leg_and_foot_disabilities = Percentage_Disability_per_County[Percentage_Disability_per_County['Lame_Missing_Hand_Missing_Foot'] != 0]

# 3. Extract the counties with Lame/Missing_Hand/Missing_Foot disability devices
counties_with_leg_and_foot_devices = Assistive_Devices[Assistive_Devices['Disability_type'] == 'Lame/Missing_Hand/Missing_Foot']
counties_with_leg_and_foot_devices = pd.DataFrame(counties_with_leg_and_foot_devices['county'].unique())
counties_with_leg_and_foot_devices

# 4. Getting the total number of counties that have people living with Lame/Missing_Hand/Missing_Foot disabilities and do not have the corresponding devices
counties_without_leg_and_foot_devices = counties_with_leg_and_foot_disabilities['county'].count() - counties_with_leg_and_foot_devices.count()
counties_without_leg_and_foot_devices

# 5. Getting the percentage of counties that have people living with Lame/Missing_Hand/Missing_Foot disabilities and do not have the corresponding devices
percentage_counties_without_leg_and_foot_devices = (counties_without_leg_and_foot_devices/counties_with_leg_and_foot_disabilities['county'].count()) * 100
print("Out of the " + str(counties_with_leg_and_foot_disabilities['county'].count()) +" counties that had Lame/Missing_Hand/Missing_Foot disabilities, "+ str(round(percentage_counties_without_leg_and_foot_devices[0],0)) + "% of them did not have the corresponding devices")

Out of the 41 counties that had Lame/Missing_Hand/Missing_Foot disabilities, 27.0% of them did not have the corresponding devices

**2.4 Obtain the percentage of the counties with 'Paralysis' disabilities and without 'Paralysis' devices.**

In [409]:
# 1. Extracting the counties that have people living with Paralysis disabilities from the Percentage_Disability_per_County dataset
counties_with_paralysis_disabilities = Percentage_Disability_per_County[Percentage_Disability_per_County['paralyzed'] != 0]

# 2. Extract the counties with Paralysis disability devices
counties_with_paralysis_devices = Assistive_Devices[Assistive_Devices['Disability_type'] == 'Paralysis']
counties_with_paralysis_devices = pd.DataFrame(counties_with_paralysis_devices['county'].unique())

# 4. Getting the total number of counties that have people living with Paralysis disabilities and do not have the corresponding devices
counties_without_paralysis_devices = counties_with_paralysis_disabilities['county'].count() - counties_with_paralysis_devices.count()
counties_without_paralysis_devices

# 5. Getting the percentage of counties that have people living with Paralysis disabilities and do not have the corresponding devices
percentage_counties_without_paralysis_devices = (counties_without_paralysis_devices/counties_with_paralysis_disabilities['county'].count()) * 100
print("Out of the " + str(counties_with_paralysis_disabilities['county'].count()) +" counties that had paralysis disabilities, "+ str(round(percentage_counties_without_paralysis_devices[0],0)) + "% of them did not have the corresponding devices")

Out of the 36 counties that had paralysis disabilities, 72.0% of them did not have the corresponding devices

**2.5 Obtain the percentage of the counties with 'Dumb' disabilities and without 'Dumb' devices.**

In [416]:
# 1. Extracting the counties that have people living with Dumb disabilities from the Percentage_Disability_per_County dataset
counties_with_dumb_disabilities = Percentage_Disability_per_County[Percentage_Disability_per_County['dumb'] != 0]

# 2. Extract the counties with Dumb disability devices
counties_with_dumb_devices = Assistive_Devices[Assistive_Devices['Disability_type'] == 'Dumb']
counties_with_dumb_devices = pd.DataFrame(counties_with_dumb_devices['county'].unique())

# 4. Getting the total number of counties that have people living with Dumb disabilities and do not have the corresponding devices
counties_without_dump_devices = counties_with_dumb_disabilities['county'].count() - counties_with_dumb_devices.count()
counties_without_dump_devices

# 5. Getting the percentage of counties that have people living with Dumb disabilities and do not have the corresponding devices
percentage_counties_without_dump_devices = (counties_without_dump_devices/counties_with_dumb_disabilities['county'].count()) * 100
print("Out of the " + str(counties_with_dumb_disabilities['county'].count()) +" counties that had dumb disabilities, "+ str(round(percentage_counties_without_dump_devices[0],0)) + "% of them did not have the corresponding devices")

Out of the 33 counties that had dumb disabilities, 88.0% of them did not have the corresponding devices

**2.6 Obtain the percentage of the counties with 'Deaf' disabilities and without 'Deaf' devices.**

In [413]:
# 1. Extracting the counties that have people living with Deaf disabilities from the Percentage_Disability_per_County dataset
counties_with_deaf_disabilities = Percentage_Disability_per_County[Percentage_Disability_per_County['deaf'] != 0]

# 2. Extract the counties with Deaf disability devices
counties_with_deaf_devices = Assistive_Devices[Assistive_Devices['Disability_type'] == 'Deaf']
counties_with_deaf_devices = pd.DataFrame(counties_with_deaf_devices['county'].unique())

# 4. Getting the total number of counties that have people living with Deaf disabilities and do not have the corresponding devices
counties_without_deaf_devices = counties_with_deaf_disabilities['county'].count() - counties_with_deaf_devices.count()
counties_without_deaf_devices

# 5. Getting the percentage of counties that have people living with Deaf disabilities and do not have the corresponding devices
percentage_counties_without_deaf_devices = (counties_without_deaf_devices/counties_with_deaf_disabilities['county'].count()) * 100
print("Out of the " + str(counties_with_deaf_disabilities['county'].count()) +" counties that had deaf disabilities, "+ str(round(percentage_counties_without_deaf_devices[0],0)) + "% of them did not have the corresponding devices")

Out of the 27 counties that had deaf disabilities, 96.0% of them did not have the corresponding devices

**2.7 Obtain the percentage of the counties with 'Mental' disabilities and without 'Mental' devices.**

In [415]:
# 1. Extracting the counties that have people living with Mental disabilities from the Percentage_Disability_per_County dataset
counties_with_mental_disabilities = Percentage_Disability_per_County[Percentage_Disability_per_County['mental'] != 0]

# 2. Extract the counties with Mental disability devices
counties_with_mental_devices = Assistive_Devices[Assistive_Devices['Disability_type'] == 'Mental']
counties_with_mental_devices = pd.DataFrame(counties_with_mental_devices['county'].unique())

# 4. Getting the total number of counties that have people living with Mental disabilities and do not have the corresponding devices
counties_without_mental_devices = counties_with_mental_disabilities['county'].count() - counties_with_mental_devices.count()


# 5. Getting the percentage of counties that have people living with Mental disabilities and do not have the corresponding devices
percentage_counties_without_mental_devices = (counties_without_mental_devices/counties_with_mental_disabilities['county'].count()) * 100
print("Out of the " + str(counties_with_mental_disabilities['county'].count()) +" counties that had mental disabilities, "+ str(round(percentage_counties_without_mental_devices[0],0)) + "% of them did not have the corresponding devices")

Out of the 40 counties that had mental disabilities, 88.0% of them did not have the corresponding devices

**2.8 Obtain the percentage of the counties with 'Blind' disabilities and without 'Blind' devices.**

In [417]:
# 1. Extracting the counties that have people living with Blind disabilities from the Percentage_Disability_per_County dataset
counties_with_blind_disabilities = Percentage_Disability_per_County[Percentage_Disability_per_County['blind'] != 0]

# 2. Extract the counties with Blind disability devices
counties_with_blind_devices = Assistive_Devices[Assistive_Devices['Disability_type'] == 'Blind']
counties_with_blind_devices = pd.DataFrame(counties_with_blind_devices['county'].unique())

# 4. Getting the total number of counties that have people living with Blind disabilities and do not have the corresponding devices
counties_without_blind_devices = counties_with_blind_disabilities['county'].count() - counties_with_blind_devices.count()

# 5. Getting the percentage of counties that have people living with Blind disabilities and do not have the corresponding devices
percentage_counties_without_blind_devices = (counties_without_blind_devices/counties_with_blind_disabilities['county'].count()) * 100
print("Out of the " + str(counties_with_blind_disabilities['county'].count()) +" counties that had blind disabilities, "+ str(round(percentage_counties_without_blind_devices[0],0)) + "% of them did not have the corresponding devices")

Out of the 29 counties that had blind disabilities, 93.0% of them did not have the corresponding devices

## 3. Identification of highly priced devices.

In [369]:
Assistive_Devices["cost_of_the_device/service_kshs"] = Assistive_Devices["cost_of_the_device/service_kshs"].str.replace("-","0")
Assistive_Devices["cost_of_the_device/service_kshs"] = Assistive_Devices["cost_of_the_device/service_kshs"].apply(pd.to_numeric)

highly_priced_devices = Assistive_Devices.sort_values(by="cost_of_the_device/service_kshs", ascending = 0)
highly_priced_devices.head(10)

,sub_county,county,disability,service_provider,cost_of_the_device/service_kshs,distributed_device/service,Disability_type
10,Isiolo,Isiolo,Physical,Association for the Physically Disabled of Ken...,495000,Power Wheelchair,Lame/Missing_Hand/Missing_Foot
135,Westlands,Nairobi,Physical,Association for the Physically Disabled of Ken...,210000,Motorised Wheelchair,Lame/Missing_Hand/Missing_Foot
146,Starehe,Nairobi,Physical,Association for the Physically Disabled of Ken...,210000,Tumaini Special Seat,Lame/Missing_Hand/Missing_Foot
19,Kajiado,Kajiado,Multiple,Association for the Physically Disabled of Ken...,200000,Folding Power Wheelchair,Other
85,Kirinyaga,Kirinyaga,Physical,Association for the Physically Disabled of Ken...,200000,Folding Power Wheelchair,Lame/Missing_Hand/Missing_Foot
201,Nairobi,Nairobi,Physical,Association for the Physically Disabled of Ken...,200000,Folding Power Wheelchair,Lame/Missing_Hand/Missing_Foot
98,Laikipia East,Laikipia,Physical,medline healthcare technologies,165000,Wheelchair,Lame/Missing_Hand/Missing_Foot
131,Lang'ata,Nairobi,Physical,Medex East Africa Ltd,160000,Electrical Wheelchair Foldable,Lame/Missing_Hand/Missing_Foot
225,Siaya,Siaya,Physical,Association for the Physically Disabled of Ken...,135980,Aluminium Wheelchair/Callipers/Surgical Shoes/...,Lame/Missing_Hand/Missing_Foot
218,Westlands,Nairobi,Physical,Therapies for Kids,130000,Physiotherapy,Lame/Missing_Hand/Missing_Foot

## 4. Identify the service provider that has more impact in distribution of devices by:

   ## 4.1. Getting the service provider that issued the highest number of devices as at June 2016;

In [370]:
# Using group by and count to identify the number of devices per issued per service_provider
service_provider = Assistive_Devices['service_provider'].groupby(Assistive_Devices['service_provider']).agg(['count'])

# Re-indexing
service_provider['Service_provider'] = service_provider.index
service_provider.reset_index(drop=True, inplace=True)

# Renaming columns
service_provider.columns = ['Total_number_of_disability_devices','Service_provider']

# Re-arranging the columns
service_provider = service_provider[['Service_provider','Total_number_of_disability_devices']]

service_provider.sort_values(by="Total_number_of_disability_devices", ascending = 0)

,Service_provider,Total_number_of_disability_devices
0,Association for the Physically Disabled of Ken...,209
17,no professional report,5
4,Garissa Orthopaedic services,3
7,Kerugoya District Hospital,3
3,Bio-Orthotic & Prosthetics services,2
15,Uasin Gishu District Hospital,2
2,Association for the Physically Disabled of Ken...,1
5,Isiolo District Hospital,1
6,Kenya Society for Deaf Children,1
8,Kitale District Hospital,1
1,Association for the Physically Disabled of Ken...,1
10,Medex East Africa Ltd,1
11,Motivation Charitable Trust,1
12,Nuga Best,1
13,Ongata Rongai Special Home Care & training Centre,1
14,Therapies for Kids,1
16,medline healthcare technologies,1
9,Kwale District Hospital,1

## 4.2 Identifying the service provider that reaches out to more counties in provision of devices

In [383]:
# Using group by and count to identify the number of devices per issued per service_provider
service_provider_counties = Assistive_Devices.groupby(['service_provider','county']).agg({'county': ['count']})
service_provider_counties

                                                                 county
                                                                  count
service_provider                                   county
Association for the Physically Disabled of Keny... Bungoma            4
                                                   Embu               1
                                                   Homa Bay           1
                                                   Isiolo             4
                                                   Kajiado            7
                                                   Kiambu            44
                                                   Kilifi             7
                                                   Kirinyaga          8
                                                   Kisumu             2
                                                   Kitui              1
                                                   Kwale              1
                                                   Laikipia           5
                                                   Machakos           4
                                                   Makueni            4
                                                   Migori             2
                                                   Mombasa           13
                                                   Murang'a           6
                                                   Nairobi           85
                                                   Nakuru             1
                                                   Narok              1
                                                   Nyamira            1
                                                   Nyeri              1
                                                   Siaya              3
                                                   Tana River         1
                                                   Tharaka Nithi      1
                                                   Uasin Gishu        1
Association for the Physically Disabled of Keny... Kiambu             1
Association for the Physically Disabled of Keny... Kwale              1
Bio-Orthotic & Prosthetics services                Wajir              2
Garissa Orthopaedic services                       Garissa            3
Isiolo District Hospital                           Isiolo             1
Kenya Society for Deaf Children                    Kiambu             1
Kerugoya District Hospital                         Kirinyaga          3
Kitale District Hospital                           Trans Nzoia        1
Kwale District Hospital                            Kwale              1
Medex East Africa Ltd                              Nairobi            1
Motivation Charitable Trust                        Nairobi            1
Nuga Best                                          Kisumu             1
Ongata Rongai Special Home Care & training Centre  Kiambu             1
Therapies for Kids                                 Nairobi            1
Uasin Gishu District Hospital                      Uasin Gishu        2
medline healthcare technologies                    Laikipia           1
no professional report                             Embu               1
                                                   Kilifi             1
                                                   Marsabit           1
                                                   Nyamira            1
                                                   Uasin Gishu        1